image: docker

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.baixing.cn

variables:
  BAX_FE_REF: registry.gitlab.baixing.cn/channel/bax-fe:$CI_BUILD_REF_NAME

stages:
  - build
  - release

build:
  stage: build
  script:
    - docker build --pull -t $BAX_FE_REF .
    - docker push $BAX_FE_REF

release:
  stage: release
  only:
    - tags
    - /^v.*$/
  script:
    - docker pull $BAX_FE_REF
    - docker tag $BAX_FE_REF
