image: docker

# before_script:
#   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.baixing.cn

variables:
  BAX_FE_REF: registry.gitlab.baixing.cn/channel/bax-fe:${CI_BUILD_REF_NAME}-${CI_PIPELINE_ID}

stages:
  - build
  - release
  - dev-deploy-auto-master
  - dev-deploy
  - prod-deploy

build:
  stage: build
  image: node
  tags:
    - k8s-dev-build
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - .npm/
  before_script:
    - npm set registry https://registry.npm.taobao.org
    - npm set disturl https://npm.taobao.org/dist
    - npm ci --cache .npm --prefer-offline
    # - npm install
  script:
    - npm run release
  artifacts:
    paths:
      - view/

release:
  stage: release
  tags:
    - k8s-dev-build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.baixing.cn
    - docker build --pull -t $BAX_FE_REF .
    - docker push $BAX_FE_REF

dev-deploy:
  stage: dev-deploy
  when: manual
  except:
    - master
  tags:
    - aliyun-k8s-dev
  script:
    - kubectl set image -n adtech deployments --selector app=bax-fe *=$BAX_FE_REF

dev-deploy-auto-master:
  stage: dev-deploy-auto-master
  only:
    - master
  tags:
    - aliyun-k8s-dev
  script:
    - kubectl set image -n adtech deployments --selector app=bax-fe *=$BAX_FE_REF

prod-deploy:
  stage: prod-deploy
  when: manual
  only:
    - master
  tags:
    - aliyun-prod-deploy
  script:
    - kubectl set image -n adtech deployments --selector app=bax-fe *=$BAX_FE_REF
