#!/usr/bin/env bash

npm run build
npm run upload
npm run release

CURRENT_VERSION=$(cat package.json \
  | grep version \
  | head -1 \
  | awk -F: '{ print $2 }' \
  | sed 's/[",]//g' \
  | tr -d '[[:space:]]')

COMMIT_MESSAGE=":boom: Release $CURRENT_VERSION :boom:"
echo $COMMIT_MESSAGE

git add view/*.html

git commit view/*.html -m 'Release'
