import {toOpt} from './fengming'

const _AUDIT_STATUS_REJECT_FROM_QUALITY = -12
const _AUDIT_STATUS_REJECT_FROM_QUALITY_WITH_KEYWORD = -13
const _AUDIT_STATUS_REJECT_FROM_SEM = -14
const _AUDIT_STATUS_NOT_STARTED = 0
const _AUDIT_STATUS_PASSED_QUALITY_ROBOT = 11
const _AUDIT_STATUS_PASSED_QUALITY = 12
const _AUDIT_STATUS_PASSED_SEM = 13

export const AUDIT_STATUS_PENDING_AUDIT = [_AUDIT_STATUS_NOT_STARTED]
export const AUDIT_STATUS_AUDITING = [_AUDIT_STATUS_PASSED_QUALITY, _AUDIT_STATUS_PASSED_QUALITY_ROBOT]
export const AUDIT_STATUS_PASS = [_AUDIT_STATUS_PASSED_SEM]
export const AUDIT_STATUS_REJECT = [_AUDIT_STATUS_REJECT_FROM_QUALITY, _AUDIT_STATUS_REJECT_FROM_QUALITY_WITH_KEYWORD, _AUDIT_STATUS_REJECT_FROM_SEM]

export const AUDIT_STATUS = {
  '待审核': AUDIT_STATUS_PENDING_AUDIT,
  '审核中': AUDIT_STATUS_AUDITING,
  '审核通过': AUDIT_STATUS_PASS,
  '审核驳回': AUDIT_STATUS_REJECT
}

export const auditStatusOpts = toOpt(AUDIT_STATUS, false, true)

const _PROMOTE_STATUS_FREEZED = -11
const _PROMOTE_STATUS_CREATED = 0
const _PROMOTE_STATUS_PENDING = 5
const _PROMOTE_STATUS_STARTED = 10
const _PROMOTE_STATUS_FINISHED = 50

export const PROMOTE_STATUS_PENDING_EDIT = [_PROMOTE_STATUS_CREATED]
export const PROMOTE_STATUS_PENDING_ONLINE = [_PROMOTE_STATUS_PENDING]
export const PROMOTE_STATUS_ONLINE = [_PROMOTE_STATUS_STARTED]
export const PROMOTE_STATUS_OFFLINE = [_PROMOTE_STATUS_FINISHED, _PROMOTE_STATUS_FREEZED]

export const PROMOTE_STATUS = {
  '待设置': PROMOTE_STATUS_PENDING_EDIT,
  '待投放': PROMOTE_STATUS_PENDING_ONLINE,
  '投放中': PROMOTE_STATUS_ONLINE,
  '已下线': PROMOTE_STATUS_OFFLINE
}

export const promoteStatusOpts = toOpt(PROMOTE_STATUS, false, true)

export const DEVICE = {
  '0': '全平台',
  '1': '电脑',
  '2': '手机',
}
