// 审核状态
export const AUDIT_STATUS_AUDITING_B2B = 'STATUS_AUDITING_B2B'
export const AUDIT_STATUS_REJECT_B2B = 'STATUS_REJECT_B2B'
export const AUDIT_STATUS_PASSED_B2B = 'STATUS_PASSED_B2B'
export const AUDIT_STATUS_AUDITING_SUPPLIES = 'STATUS_AUDITING_SUPPLIES'
export const AUDIT_STATUS_REJECT_SUPPLIES = 'STATUS_REJECT_SUPPLIES'
export const AUDIT_STATUS_PASSED_SUPPLIES = 'STATUS_PASSED_SUPPLIES'
export const AUDIT_STATUS_AUDITING_SEM = 'STATUS_AUDITING_SEM'
export const AUDIT_STATUS_REJECT_SEM = 'STATUS_REJECT_SEM'
export const AUDIT_STATUS_PASSED_SEM = 'STATUS_PASSED_SEM'

export const AUDIT_STATUS_MAPPING = {
    [AUDIT_STATUS_AUDITING_B2B]: 'B2B词审核中',
    [AUDIT_STATUS_REJECT_B2B]: 'B2B词审核不通过',
    [AUDIT_STATUS_PASSED_B2B]: 'B2B词审核通过',
    [AUDIT_STATUS_AUDITING_SUPPLIES]: '物料审核中',
    [AUDIT_STATUS_REJECT_SUPPLIES]: '物料审核不通过',
    [AUDIT_STATUS_PASSED_SUPPLIES]: '物料审核通过',
    [AUDIT_STATUS_AUDITING_SEM]: 'sem代理商审核中',
    [AUDIT_STATUS_REJECT_SEM]: 'sem代理商审核不通过',
    [AUDIT_STATUS_PASSED_SEM]: 'sem代理商审核通过'
}